#ifndef PCPD_MSG_HL2REMOTECONTROL
#define PCPD_MSG_HL2REMOTECONTROL

#include "pcpd_msgs/msg/Types.idl"

module pcpd_msgs {
  module msg {

    enum Hololens2RemoteCommand {
      RC_MSG_GetApplicationVersion,
      RC_MSG_GetUTCOffset,
      RC_MSG_SetHSMarkerState,
      RC_MSG_GetPVSubsystemStatus,
      RC_MSG_SetPVFocus,
      RC_MSG_SetPVVideoTemporalDenoising,
      RC_MSG_SetPVWhiteBalancePreset,
      RC_MSG_SetPVWhiteBalanceValue,
      RC_MSG_SetPVExposure,
      RC_MSG_SetPVExposurePriorityVideo,
      RC_MSG_SetPVIsoSpeed,
      RC_MSG_SetPVBacklightCompensation,
      RC_MSG_SetPVSceneMode
    };


    struct Hololens2RCRequest {
      Hololens2RemoteCommand type;
      uint32 payload_len;
      sequence<uint8> payload;
    };


    struct Hololens2RCResponse {
      Hololens2RemoteCommand type;
      uint32 payload_len;
      sequence<uint8> payload;
    };


  };
};

#endif
